### ISSUE TITLE
versione csv

### ISSUE THREAD

**Issue by Giuliano69** [heyteacher/COVID-19#1]
Buongiorno,
sarebbe utile se i file fossero disponibili ANCHE in formato csv (molto più aperto e confrontabile con quelli di "origine" della protezione civile".

Chiedo anche se i numeri così elaborati coincidono con
https://www.who.int/emergencies/diseases/novel-coronavirus-2019/situation-reports/

Cordialmente

**Comment by heyteacher** [comment]
Domani rilascio i CSV con l'estensioni. 
Ho controllato quelli del 17 marzo, i dati coincidono con quelli del WHO sono un giorno indietro (18 marzo nel report). Sicoramente i dati del WHO sono presi e rielaborati dal repository ufficiale della Protezione Civile.

**Comment by heyteacher** [comment]
Sono disponibili i CSV con le estensioni calcolate a partire dal 19/03 a breve elaboro il backlog.
Fatemi sapere se trovate incongruenze sui dati.
Grazie
