### ISSUE TITLE
modello SIR

### ISSUE THREAD

**Issue by Giuliano69** [heyteacher/COVID-19#2]
Modello SIR
Nei modelli statistici canonici delle epidemie, si usa distinguere tra Sani(suscettibili), Infetti e Rimossi (morti& guariti).

Il campo della protezione civile “totale_attualmente_positivi” corrisponde al conteggio giornaliero degli infetti, salvo quelli asintomatici. 
Questo valore potrebbe essere indicato più propriamente nel grafico come “infetti (giornalieri)”.

Nei grafici dell’ “andamento” mancano i guariti; si potrebbe pensare se accorparli con i deceduti, nell’unico campo “Rimossi” per aumentare la leggibilità del grafico

Si potrebbe ANCHE creare un grafico SIR, con una simulazione dell’andamento della epidemia con i vari R0=2,5; 2,7; 3,0,… confrontato con l’andamento reale….

**Comment by heyteacher** [comment]
Grazie per gli utili consigli sulla nomenclatura, ho anche intenzione di riorganizzare i grafici ora sono un pò caotici è introdurre anche i guariti. 
Un consiglio, dove posso trovare le formule R0=2,5; 2,7; 3,0 spiegate per non addetti?

**Comment by carlobellettini** [comment]
una altra cosa che potrebbe essere utile è dare la possibilità di avere i grafici in scala logaritmica... che è spesso più chiara in questi casi

**Comment by heyteacher** [comment]
purtroppo https://swimlane.gitbook.io/ngx-charts/ non supporta le scala logaritmica. Vabbè, la prossima pandemia userò https://plotly.com/javascript/

**Comment by carlobellettini** [comment]
grazie lo stesso

PS comunque anche se non è supportato dalla libreria grafica, per disegnarlo e vedere l'andamento basterebbe che ti calcolassi un'altra colonna con come valore il logaritmo del dato originale

**Comment by heyteacher** [comment]
Ok, ma ngx-charts non mi permette di applicare l'inverso del logaritmo sul valore visualizzato ma solo sull'asse delle ordinate. Quindi la popup sul grafico visualizzebbe il valore del logaritmo anzichè il valore reale
