### ISSUE TITLE
suddivisione nord-centro-sud

### ISSUE THREAD

**Issue by Giuliano69** [heyteacher/COVID-19#3]
Lancio una ulteriore idea per una analisi dei dati totali italiani.
E' possibile (e temibile) che di fronte ad un calo dei contagi al nord, inizino quelli al centro e poi quelli al sud.
Considerando SOLO i totali, questo fenomeno non si noterebbe, e si avrebbe una sostanziale costanza o incremento, mentre essendo l'epidemia sfasata temporalmente&regionalmente, aiuterebbe suddividere i dati italiani per seguire meglio l'evoluzione di una pandemia, secondo la classica suddivisione istat  https://www.tuttitalia.it/statistiche/nord-centro-mezzogiorno-italia/ ..:
Graf1a- casi totali italiani (+ casi tot nord + casi tot centro + casi tot sud)
Graf1b- andamento nuovi infetti giornalieri ( + andamento nuovi infetti nord + andamento nuovi infetti centro +andamento nuovi infetti sud)
Cosa ne pensi ?

**Comment by heyteacher** [comment]
ho aggiunto il grafico con la percentuale giornaliera di nuovi casi per regione, che evidenzia proprio la tendenza di aumento al centro - sud.
https://heyteacher.github.io/COVID-19

![Screenshot from 2020-03-26 13-00-34](https://user-images.githubusercontent.com/51722388/77645359-e5235e80-6f62-11ea-9939-f8b5795e7bdb.png)
